version: '3.9'

services:
  web:
    image: node:20-alpine
    command: >
      sh -c "cd /app &&
             npm install --legacy-peer-deps &&
             npm run dev"
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 5173:5173
 