name: Deploy to Dokku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dokku
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ vars.REMOTE_URL }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
